# Generated by Django 5.2.10 on 2026-01-24 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_address_address_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingDetail',
        ),
    ]
