# Generated by Django 5.2.10 on 2026-01-25 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
