# Generated by Django 6.0.1 on 2026-01-18 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('0-3M', '0–3 Months'), ('3-6M', '3–6 Months'), ('6-12M', '6–12 Months'), ('1-2Y', '1–2 Years'), ('2-3Y', '2–3 Years'), ('3-4Y', '3–4 Years'), ('4-5Y', '4–5 Years')], max_length=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.product')),
            ],
        ),
    ]
