# Generated by Django 6.0.1 on 2026-01-19 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_cartitem_variant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
