# Generated by Django 6.0.1 on 2026-01-20 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_cartitem_variant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'variant')},
        ),
    ]
