# Generated by Django 5.2.10 on 2026-01-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='discount_percentage',
            field=models.IntegerField(default=0, help_text='Enter discount % (e.g. 10 for 10%)'),
        ),
    ]
